# Site settings
title: klinster
username: klinster
email: contact@klinster.net
description: ""
baseurl:
url: "http://klinster.net"
paginate: 5
gaaccount: UA-52059311-1

# Build settings
markdown: kramdown
permalink: pretty
